import { Product } from './types';

export const IDR_TO_USD = 16000;

export const formatPrice = (priceIdr: number) => ({
  usd: `$${(priceIdr / IDR_TO_USD).toFixed(2)}`,
  idr: `Rp ${priceIdr.toLocaleString('id-ID')}`
});

export const products: Product[] = [
  {
    id: 1,
    name: "Arabica Blend",
    nameId: "Arabica Blend",
    price: 85000,
    weight: "250g",
    roastLevel: "Medium Dark",
    origin: "Indonesia",
    flavorNotes: ["Chocolate", "Nutty"],
    flavorNotesId: ["Cokelat", "Kacang"],
    description: "Premium Arabica Blend by Kopi Babh Kacamata. Medium-dark roast revealing deep chocolate and nutty notes.",
    descriptionId: "Premium Arabica Blend dari Kopi Babh Kacamata. Sangrai medium-dark memunculkan cita rasa cokelat dan kacang yang pekat.",
    rating: 5.0,
    reviews: 42,
    stock: 50,
    isNew: true,
    badge: "NEW",
    image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 2,
    name: "Arabica Blend (Java Origin)",
    nameId: "Arabica Blend (Asal Jawa)",
    price: 80000,
    weight: "250g",
    roastLevel: "Medium",
    origin: "Java",
    flavorNotes: ["Chocolate", "Nutty"],
    flavorNotesId: ["Cokelat", "Kacang"],
    description: "Single origin Java Arabica Blend. Medium roast with smooth chocolate and nutty flavor profiles. Grown at 1200M elevation.",
    descriptionId: "Kopi single origin Arabica Jawa. Sangrai medium dengan profil rasa cokelat dan kacang yang halus. Ditanam di ketinggian 1200M.",
    rating: 4.8,
    reviews: 86,
    stock: 75,
    isNew: false,
    badge: "POPULAR",
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 3,
    name: "Black Coffe",
    nameId: "Black Coffe",
    price: 75000,
    weight: "250g",
    roastLevel: "Dark",
    origin: "Sumatra",
    flavorNotes: ["Earthy", "Rich"],
    flavorNotesId: ["Earthy", "Kaya Rasa"],
    description: "Signature Black Coffe from Sumatra. Dark roasted for an intense, earthy, and rich experience.",
    descriptionId: "Kopi Hitam khas dari Sumatra. Disangrai gelap untuk pengalaman rasa yang intens, earthy, dan kaya.",
    rating: 4.9,
    reviews: 120,
    stock: 100,
    isNew: false,
    badge: "BESTSELLER",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 4,
    name: "Supper Coffe",
    nameId: "Supper Coffe",
    price: 90000,
    weight: "250g",
    roastLevel: "Medium Dark",
    origin: "Eupamato",
    flavorNotes: ["Classic", "Strong"],
    flavorNotesId: ["Klasik", "Kuat"],
    description: "Supper Coffe blend by Kopi Babh Kacamata. A uniquely crafted roast for a strong classic taste.",
    descriptionId: "Campuran Supper Coffe oleh Kopi Babh Kacamata. Sangrai yang diracik khusus untuk rasa klasik yang kuat.",
    rating: 4.7,
    reviews: 34,
    stock: 40,
    isNew: false,
    badge: null,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
  }
];

export const translations: Record<'en' | 'id', Record<string, string>> = {
  en: {
    "Add to Cart": "Add to Cart",
    "Buy Now": "Buy Now",
    "Shopping Cart": "Shopping Cart",
    "Checkout": "Checkout",
    "About Us": "About Us",
    "Marketplace": "Marketplace",
    "Our Products": "Our Products",
    "Product Details": "Product Details",
    "Shipping To": "Shipping To",
    "Payment Method": "Payment Method",
    "Order Summary": "Order Summary",
    "Place Order": "Place Order",
    "Back to Shop": "Back to Shop",
    "Weight": "Weight",
    "Roast Level": "Roast Level",
    "Origin": "Origin",
    "Flavor Notes": "Flavor Notes",
    "In Stock": "In Stock",
    "Out of Stock": "Out of Stock",
    "Subtotal": "Subtotal",
    "Shipping Cost": "Shipping Cost",
    "Total": "Total",
    "Quantity": "Quantity",
    "HOME": "HOME",
    "ABOUT": "ABOUT",
    "FREE SHIPPING OVER $50": "FREE SHIPPING OVER $50",
    "FRESH ROASTED WEEKLY": "FRESH ROASTED WEEKLY",
    "ETHICALLY SOURCED FROM CENTRAL JAVA": "ETHICALLY SOURCED FROM CENTRAL JAVA",
    "SHOP NOW": "SHOP NOW",
    "OUR STORY": "OUR STORY",
    "CART EMPTY": "CART EMPTY",
    "GO TO SHOP": "GO TO SHOP",
    "PROCEED TO CHECKOUT": "PROCEED TO CHECKOUT",
    "ORDER CONFIRMED!": "ORDER CONFIRMED!",
    "CONTINUE SHOPPING": "CONTINUE SHOPPING",
    "THE STORY": "THE STORY",
    "ALL": "ALL",
    "LIGHT": "LIGHT",
    "MEDIUM": "MEDIUM",
    "DARK": "DARK"
  },
  id: {
    "Add to Cart": "Tambah ke Keranjang",
    "Buy Now": "Beli Sekarang",
    "Shopping Cart": "Keranjang Belanja",
    "Checkout": "Bayar Sekarang",
    "About Us": "Tentang Kami",
    "Marketplace": "Toko",
    "Our Products": "Produk Kami",
    "Product Details": "Detail Produk",
    "Shipping To": "Kirim Ke",
    "Payment Method": "Metode Pembayaran",
    "Order Summary": "Ringkasan Pesanan",
    "Place Order": "Pesan Sekarang",
    "Back to Shop": "Kembali ke Toko",
    "Weight": "Berat",
    "Roast Level": "Level Roast",
    "Origin": "Asal",
    "Flavor Notes": "Catatan Rasa",
    "In Stock": "Tersedia",
    "Out of Stock": "Habis",
    "Subtotal": "Subtotal",
    "Shipping Cost": "Ongkos Kirim",
    "Total": "Total",
    "Quantity": "Jumlah",
    "HOME": "BERANDA",
    "ABOUT": "TENTANG",
    "FREE SHIPPING OVER $50": "GRATIS ONGKIR DI ATAS $50",
    "FRESH ROASTED WEEKLY": "DISANGRAI SEGAR TIAP MINGGU",
    "ETHICALLY SOURCED FROM CENTRAL JAVA": "DARI SUMBER ETIS DI JAWA TENGAH",
    "SHOP NOW": "BELANJA",
    "OUR STORY": "CERITA KAMI",
    "CART EMPTY": "KERANJANG KOSONG",
    "GO TO SHOP": "KEMBALI KE TOKO",
    "PROCEED TO CHECKOUT": "LANJUT PEMBAYARAN",
    "ORDER CONFIRMED!": "PESANAN DIKONFIRMASI!",
    "CONTINUE SHOPPING": "LANJUT BELANJA",
    "THE STORY": "CERITA",
    "ALL": "SEMUA",
    "LIGHT": "RINGAN",
    "MEDIUM": "SEDANG",
    "DARK": "GELAP"
  }
};
